<a href="https://colab.research.google.com/github/2303A51494/23CSBT27/blob/main/Array1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

creation Array and array operation

In [2]:
import numpy as np
arry=np.array([2,5,3,7,3])
print(arry)
print(type(arry))

[2 5 3 7 3]
<class 'numpy.ndarray'>


In [3]:
import numpy as np
arry1=np.array({'apple','banana','orange'})
print(arry1)
print(type(arry1))

{'apple', 'orange', 'banana'}
<class 'numpy.ndarray'>


In [5]:
import numpy as np
arry=np.array([[2,5],[4,2]])
arry1=np.array([[2,5,4,2],[4,2,1,0]])
arry2=np.array([[2,5,4],[4,2,5],[6,7,8]])
print(arry)
print(arry1)
print(arry2)


[[2 5]
 [4 2]]
[[2 5 4 2]
 [4 2 1 0]]
[[2 5 4]
 [4 2 5]
 [6 7 8]]


In [7]:
import numpy as np
arry1=np.array([1,3,4,5,6])
arry2=np.array([2,6,3,4,3])
print(arry)
print(np.add(arry1,arry2))
print(np.multiply(arry1,arry2))
print(np.subtract(arry1,arry2))
print(np.divide(arry1,arry2))
print(type(arry))

[[2 5]
 [4 2]]
[3 9 7 9 9]
[ 2 18 12 20 18]
[-1 -3  1  1  3]
[0.5        0.5        1.33333333 1.25       2.        ]
<class 'numpy.ndarray'>


In [8]:
import numpy as np
arry1=np.array({'apple','banana','orange'})
print(arry1)
print(type(arry1))


{'apple', 'orange', 'banana'}
<class 'numpy.ndarray'>
